// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCqk_HeIFKM0xjOmMsqKzGx86VfEtS4Eg',
    appId: '1:507169574109:android:89ca3d5fa56a74fe555f34',
    messagingSenderId: '507169574109',
    projectId: 'fir-flutter-auth-cdff2',
    storageBucket: 'fir-flutter-auth-cdff2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPJNrfACG3fJ4Z4anQ53rUJxqlrqAk3kw',
    appId: '1:507169574109:ios:ba07109e22d2b107555f34',
    messagingSenderId: '507169574109',
    projectId: 'fir-flutter-auth-cdff2',
    storageBucket: 'fir-flutter-auth-cdff2.appspot.com',
    androidClientId: '507169574109-g5mu8hcicsmi3648toq2djge8vquff6d.apps.googleusercontent.com',
    iosClientId: '507169574109-cku19b0so89k7o4pkkkfnrku7s2vt4ue.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPJNrfACG3fJ4Z4anQ53rUJxqlrqAk3kw',
    appId: '1:507169574109:ios:ba07109e22d2b107555f34',
    messagingSenderId: '507169574109',
    projectId: 'fir-flutter-auth-cdff2',
    storageBucket: 'fir-flutter-auth-cdff2.appspot.com',
    androidClientId: '507169574109-g5mu8hcicsmi3648toq2djge8vquff6d.apps.googleusercontent.com',
    iosClientId: '507169574109-cku19b0so89k7o4pkkkfnrku7s2vt4ue.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
